apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: cache
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: demoapp-flask
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: cache
  labels:
    app: demoapp
spec:
  selector:
    app: demoapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
